export const loadDagFuncList = [
    [
        "funcs",
        "apply_fitted_model"
    ],
    [
        "funcs",
        "assert_dims"
    ],
    [
        "funcs",
        "clean_dict"
    ],
    [
        "funcs",
        "consecutive_indices"
    ],
    [
        "funcs",
        "create_kfold_matrix"
    ],
    [
        "funcs",
        "dataset_train_test_split"
    ],
    [
        "funcs",
        "dflt_featurizer"
    ],
    [
        "funcs",
        "dflt_filter"
    ],
    [
        "funcs",
        "fixed_step_chunker"
    ],
    [
        "funcs",
        "get_groups_extremities_all"
    ],
    [
        "funcs",
        "indices_for_percentile"
    ],
    [
        "funcs",
        "k_fold_scores"
    ],
    [
        "funcs",
        "learn_outlier_model"
    ],
    [
        "funcs",
        "mk_chunker_step"
    ],
    [
        "funcs",
        "mk_featurizer_step"
    ],
    [
        "funcs",
        "mk_pipeline"
    ],
    [
        "funcs",
        "mk_simple_model"
    ],
    [
        "funcs",
        "mk_step"
    ],
    [
        "funcs",
        "modify_pipeline"
    ],
    [
        "funcs",
        "modify_step"
    ],
    [
        "funcs",
        "name_of_obj"
    ],
    [
        "funcs",
        "projector"
    ],
    [
        "funcs",
        "scores_to_intervals"
    ],
    [
        "funcs",
        "simple_chunker"
    ],
    [
        "funcs",
        "simple_featurizer"
    ],
    [
        "funcs",
        "tagged_sounds_to_single_array"
    ],
    [
        "dags",
        "sample_1"
    ],
    [
        "dags",
        "test_dag_sprint_review"
    ]
];